server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aameiwei/aispringcloud.git
          searchPaths: config
          username: 923070686@qq.com
          password: wojiaoxiaowei824
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
